spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cinetalk-back-database:3306/cinetalk-back
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: cinetalk-back-redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate # prod 배포시 validate
    show-sql: true

cinetalk:
  back:
    base:
      url: http://3.37.21.244/dir/ # aws ec2 탄력적 ip로 변경