spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common
---

spring:
  config:
    activate:
      on-profile: common

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cinetalk-back
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cinetalk-back-database:3306/cinetalk-back
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: cinetalk-back-redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

cinetalk:
  back:
    base:
      url: http://3.37.21.244/

