name: cinetalk-back-cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.YML }}"
        shell: bash

      - name: Gradle Cashing
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: |
         chmod +x gradlew
         sudo systemctl start docker
         sudo chmod +x /usr/local/bin/docker-compose
         sudo chmod 666 /var/run/docker.sock
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u kallis0926 -p alemal@!34
          docker build -t kallis0926/cinetalk-back-app:0.1 .
          docker push kallis0926/cinetalk-back-app:0.1

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.CINETALK_BACK_BASE_URL }}
          username: ec2-user
          key: ${{ secrets.CINETALK_BACK_KEY_WINDOWS }}
          port: 22
          script: |
            docker login -u kallis0926 -p ${{ secrets.DOCKER_PASSWORD }}
            docker rm $(docker ps -a -q)
            docker rmi kallis0926/cinetalk-back-app:0.1
            docker pull kallis0926/cinetalk-back-app:0.1
            docker-compose up -d --build