name: cinetalk-back-cicd
on:
  push:
    branches:
    - main

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: docker-compose
      - run: echo welcome
      # - run: docker-compose.yml
